### ISSUE TITLE
error Cannot enable Hyper-V service - fresh install of edge

### ISSUE THREAD

**Issue by hicreate** [docker/docs#10720]
### Problem description

Docker Edge throws an error after installation "error - Cannot enable Hyper-V service" even though Hyper V is enabled in Control Panel Windows Features.

### Problem location

Other: immediately after install on Windows 10 Pro

### Project version(s) affected

Print out from docker version on powershell -

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Suggestions for a fix

I have tried disabling Hyper-v in the control panel, restarting, then enabling and restarting but no luck. I also could not get docker stable to work with linux containers, only windows containers but I have since uninstalled stable for edge.

**Comment by hicreate** [comment]
I cannot get the application to open to get the diagnosis info unfortunately.

**Comment by danielskeeled** [comment]
@hicreate had the same issue and it turned out that virtualization wasn't enabled on the firmware.
[This fixed my problem](https://superuser.com/a/648237)

**Comment by arturz** [comment]
@hicreate struggled with it for a while. Type in cmd ```bcdedit``` and make sure you have ```hypervisorlaunchtype    Auto```.

```bcdedit /set hypervisorlaunchtype auto``` fixed my problem.

**Comment by MuhammadRoheel** [comment]
same issue, Hyper-v is enabled in windows, virtualization is enabled in hardware setup, still throwing this error.

**Comment by haydenhancock** [comment]
Same for me.

Client: Docker Desktop Community
Version: 2.3.0.3
OS: Windows 10 Pro
CPU: AMD Ryzen 9 3900x 12-Core Processor
RAM: 32.0 GB

Hyper-V is running and I even see the "DockerDesktopVM" in Hyper-V but continue to get this error.

**Comment by sourav-code-space** [comment]
Having the same problem with Docker desktop on my Windows 10 Enterprise. Software installation on Windows machine getting more painful day by day. No proper fix, lots of issues. Really frustrating.

**Comment by hicreate** [comment]
The issue hasn't even been acknowledged, let alone assigned so I hold out no hope that any support is going to be forthcoming.
